apiVersion: v1
kind: Secret
metadata:
  name: simplifiedorleanssecrets
type: Opaque
data:
  ApplicationInsights__InstrumentationKey: {{ .Values.appInsightsInstrumentationKey | b64enc }}
  CosmosDb__AccountEndpoint: {{ .Values.cosmosDbAccountEndpoint | b64enc }}
  CosmosDb__AccountKey: {{ .Values.cosmosDbAccountKey | b64enc }}
stringData:
  CosmosDb__DB: {{ .Values.cosmosDbDatabaseId }}
  CosmosDb__DatabaseId: {{ .Values.cosmosDbDatabaseId }}
  CosmosDb__Collection: {{ .Values.cosmosDbClusteringContainerId }}
  CosmosDb__ContainerId: {{ .Values.cosmosDbEventsContainerId }}