# Default values for apisilohost.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

autoscaling:
  enabled: false

replicaCount: 3

image:
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80